// Generated by gencpp from file tutorial2/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TUTORIAL2_MESSAGE_ADDTWOINTS_H
#define TUTORIAL2_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <tutorial2/AddTwoIntsRequest.h>
#include <tutorial2/AddTwoIntsResponse.h>


namespace tutorial2
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace tutorial2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tutorial2::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::tutorial2::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::tutorial2::AddTwoInts > {
  static const char* value()
  {
    return "tutorial2/AddTwoInts";
  }

  static const char* value(const ::tutorial2::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::tutorial2::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::tutorial2::AddTwoInts >
template<>
struct MD5Sum< ::tutorial2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial2::AddTwoInts >::value();
  }
  static const char* value(const ::tutorial2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial2::AddTwoIntsRequest> should match
// service_traits::DataType< ::tutorial2::AddTwoInts >
template<>
struct DataType< ::tutorial2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::tutorial2::AddTwoInts >::value();
  }
  static const char* value(const ::tutorial2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tutorial2::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::tutorial2::AddTwoInts >
template<>
struct MD5Sum< ::tutorial2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial2::AddTwoInts >::value();
  }
  static const char* value(const ::tutorial2::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial2::AddTwoIntsResponse> should match
// service_traits::DataType< ::tutorial2::AddTwoInts >
template<>
struct DataType< ::tutorial2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::tutorial2::AddTwoInts >::value();
  }
  static const char* value(const ::tutorial2::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUTORIAL2_MESSAGE_ADDTWOINTS_H
